Add health check endpoint
riotkit-org/backup-repository pull request #187
Opened 2022-02-27 22:57 UTC by keskad

Resolves: #186

2022-02-27 22:57 UTC, keskad commented
@blackandred

2022-02-28 06:59 UTC, blackandred requested changes
Missing cluster connectivity check - actually should check if ConfigurationProvider works

2022-02-28 21:49 UTC, keskad commented
Sorry, indeed it was missing. Added.

2022-02-28 21:52 UTC, blackandred approved these changes
Looks and works fine.

2022-02-28 21:53 UTC, merged